artifacts_root: artifacts

data_ingestion:
  data_ingestion_dir: artifacts/data_ingestion
  test_data_url: https://drive.google.com/file/d/1Dy1CmtS30nSa2lxgBr-VK_ufMz7AXpV9
  train_data_url: https://drive.google.com/file/d/1dYWh2YlTwtbnPbN6bcOOJgR011W0fWwx
  train_data_path: artifacts/data_ingestion/raw_data
  test_data_path: artifacts/data_ingestion/raw_data

data_validation:
  data_validation_dir: artifacts/data_validation
  train_data_path: artifacts/data_ingestion/raw_data/home_insurance_train.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  data_transformation_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/raw_data/home_insurance_train.csv
  processed_data_path: artifacts/data_transfrmation/transformed_data